name: Build Kivy App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        description: 'Trigger the build'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython kivy

    - name: Build APK
      run: |
        python -m pip install buildozer
        buildozer init
        buildozer -v android debug
